[package]
name = "bouncing-ball"
version = "1.0.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3", features = ["wayland"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
